### ISSUE TITLE
How I shoud to use it into a template?

### ISSUE THREAD

**Issue by gfdesign** [JoeHana/polylang-conditional#1]
Dear Joe
Could you explaime how to use your plugin into a template?
I have two language in my site: English and Spanish
Looking forward to your comments
Best regards

**Comment by JoeHana** [comment]
Hey, this plugin basically adds a template function and a shortcode. In a template file you can use it like:

`if( is_language( 'es' ) ) {
    // execute code
}`

Same basically for the shortcode within your editor or widget:

`[is_language lang="en"]My Content[/is_language]`

See also the info here:
* https://github.com/JoeHana/polylang-conditional
